# Drop-in for /etc/pacman.d/max-arch.conf
#
# sudo cp pacman-max-arch.conf /etc/pacman.d/max-arch.conf
# Then add to /etc/pacman.conf:
#   Include = /etc/pacman.d/max-arch.conf
# sudo pacman -Sy

[max-arch]
SigLevel = Optional TrustAll
Server = https://gaavin.github.io/max-arch/$arch
